var o, p;
o = [
	Dictionary.prNew,  Array.prNew(64),  Array.prNew(7),  Array.prNew(7),  
	Array.prNew(5),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(5),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(15),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(7),  Array.prNew(7),  "CLAVE",  
	"CASCARA",  "SHEKERE",  "",  "",  
	"LLAMADOR",  "LLAMADOR",  Array.prNew(7),  Array.prNew(7),  
	Array.prNew(7),  Array.prNew(7),  Array.prNew(7),  Array.prNew(7)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 11 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[2],  
		'rhythms',  o[3],  nil,  nil,  
		'bpm',  131.09717868339,  'indices',  o[41],  
		'trackNames',  o[42],  'humAmp',  o[50],  
		nil,  nil,  nil,  nil,  
		'pitches',  o[51],  'humTime',  o[52],  
		nil,  nil,  'volumes',  o[53],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[54],  nil,  nil,  
		nil,  nil,  'sampleIndices',  o[55],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ false,  true,  false,  false,  
		false,  false,  true ],  
	// Array
	3, [ o[4],  o[10],  o[16],  o[19],  
		o[19],  o[21],  o[37] ],  
	// Array
	4, [ o[5],  o[6],  o[7],  o[8],  
		o[9] ],  
	// Array
	5, [ 0.75,  2,  1 ],  
	// Array
	6, [ 1,  2,  1 ],  
	// Array
	7, [ 0.7,  2,  1 ],  
	// Array
	8, [ 0.55,  2,  1 ],  
	// Array
	9, [ 1,  2,  1 ],  
	// Array
	10, [ o[11],  o[12],  o[13],  o[14],  
		o[15] ],  
	// Array
	11, [ 0.66666666666667,  4,  1 ],  
	// Array
	12, [ 1.0,  4,  1 ],  
	// Array
	13, [ 0.66666666666667,  4,  1 ],  
	// Array
	14, [ 0.66666666666667,  4,  1 ],  
	// Array
	15, [ 1.0,  4,  1 ],  
	// Array
	16, [ o[17],  o[18] ],  
	// Array
	17, [ 0.66666666666667,  7,  1 ],  
	// Array
	18, [ 0.33333333333333,  8,  1 ],  
	// Array
	19, [ o[20] ],  
	// Array
	20, [ 4,  0,  0 ],  
	// Array
	21, [ o[22],  o[23],  o[24],  o[25],  
		o[26],  o[27],  o[28],  o[29],  
		o[30],  o[31],  o[32],  o[33],  
		o[34],  o[35],  o[36] ],  
	// Array
	22, [ 0.25,  1,  0.25 ],  
	// Array
	23, [ 0.25,  10,  0.25 ],  
	// Array
	24, [ 0.25,  10,  0.25 ],  
	// Array
	25, [ 0.25,  1,  0.25 ],  
	// Array
	26, [ 0.25,  1,  0.25 ],  
	// Array
	27, [ 0.25,  10,  0.25 ],  
	// Array
	28, [ 0.25,  10,  0.25 ],  
	// Array
	29, [ 0.25,  10,  1 ],  
	// Array
	30, [ 0.5,  3,  1 ],  
	// Array
	31, [ 0.25,  10,  0.5 ],  
	// Array
	32, [ 0.25,  1,  0.5 ],  
	// Array
	33, [ 0.25,  1,  0.25 ],  
	// Array
	34, [ 0.25,  10,  0.25 ],  
	// Array
	35, [ 0.25,  10,  0.25 ],  
	// Array
	36, [ 0.25,  1,  0.25 ],  
	// Array
	37, [ o[38],  o[39],  o[40] ],  
	// Array
	38, [ 0.66666666666667,  1,  0.43 ],  
	// Array
	39, [ 0.33333333333333,  3,  1 ],  
	// Array
	40, [ 1,  3,  1 ],  
	// Array
	41, [ 1,  3,  13,  0,  
		0,  20,  22 ],  
	// Array
	42, [ o[43],  o[44],  o[45],  o[46],  
		o[47],  o[48],  o[49] ],  
	// Array
	50, [ 0.14237288135593,  0.14237288135593,  0.14237288135593,  0.14237288135593,  
		0.14237288135593,  0.14237288135593,  0.14237288135593 ],  
	// Array
	51, [ 46.0,  60,  62.0,  60,  
		62.0,  62.0,  59.0 ],  
	// Array
	52, [ 0.0033898305084746,  0.0033898305084746,  0.0033898305084746,  0.0033898305084746,  
		0.0033898305084746,  0.0033898305084746,  0.0033898305084746 ],  
	// Array
	53, [ 0.54130277195509,  0.82327578815141,  0.84838200482362,  0.001,  
		0.001,  1.4962356560944,  0.76216197125196 ],  
	// Array
	54, [ 0.19067796610169,  0.19067796610169,  0.19067796610169,  0.19067796610169,  
		0.22727272727273,  0.19067796610169,  0.19067796610169 ],  
	// Array
	55, [ 0,  1,  2,  3,  
		4,  5,  0 ]
];
prUnarchive(o,p);
