var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(9),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(2),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  
	Array.prNew(4),  Array.prNew(3),  Array.prNew(3),  "llcmp",  
	Array.prNew(3),  Array.prNew(3),  "llaf",  Array.prNew(4),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "llaf",  Array.prNew(1),  Array.prNew(3),  
	Array.prNew(1),  Array.prNew(3),  Array.prNew(9),  "CLAVE",  
	"CATA",  "SHEKERE",  "",  "",  
	"LLAMADOR",  "GOLPE",  "CLAVE",  "CLAVE",  
	Array.prNew(9),  Dictionary.prNew,  Array.prNew(88),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[42],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[52],  'temaBpm',  118.62676056338,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[53],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[55],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[56],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[66],  
		nil,  nil,  nil,  nil,  
		'indices',  o[67],  nil,  nil,  
		nil,  nil,  'humAmp',  o[68],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[69],  
		nil,  nil,  'volumes',  o[70],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[71],  nil,  nil,  
		'montunoIndices',  o[72],  'sampleIndices',  o[73],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[74],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[19],  o[22],  
		o[22],  o[24],  o[31],  o[38],  
		o[40] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.66666666666667,  4,  1 ],  
	// Array
	5, [ 1.0,  4,  1 ],  
	// Array
	6, [ 0.66666666666667,  4,  1 ],  
	// Array
	7, [ 0.66666666666667,  4,  1 ],  
	// Array
	8, [ 1.0,  4,  1 ],  
	// Array
	9, [ o[10],  o[11],  o[12],  o[13],  
		o[14],  o[15],  o[16],  o[17],  
		o[18] ],  
	// Array
	10, [ 0.25,  4,  0 ],  
	// Array
	11, [ 0.25,  4,  1 ],  
	// Array
	12, [ 0.5,  4,  1 ],  
	// Array
	13, [ 0.5,  4,  0 ],  
	// Array
	14, [ 0.5,  4,  0 ],  
	// Array
	15, [ 0.5,  4,  1 ],  
	// Array
	16, [ 0.5,  4,  1 ],  
	// Array
	17, [ 0.75,  4,  0 ],  
	// Array
	18, [ 0.25,  4,  1 ],  
	// Array
	19, [ o[20],  o[21] ],  
	// Array
	20, [ 0.66666666666667,  7,  1 ],  
	// Array
	21, [ 0.33333333333333,  8,  1 ],  
	// Array
	22, [ o[23] ],  
	// Array
	23, [ 4,  0,  0 ],  
	// Array
	24, [ o[25],  o[26],  o[28],  o[29] ],  
	// Array
	25, [ 0.33333333333333,  0,  0 ],  
	// Array
	26, [ 0.66666666666667,  o[27],  1 ],  
	// Array
	28, [ 0.33333333333333,  0,  0 ],  
	// Array
	29, [ 0.66666666666667,  o[30],  1 ],  
	// Array
	31, [ o[32],  o[33],  o[34],  o[36] ],  
	// Array
	32, [ 2.0,  0,  0 ],  
	// Array
	33, [ 0.66666666666667,  0,  0 ],  
	// Array
	34, [ 0.33333333333333,  o[35],  1 ],  
	// Array
	36, [ 1.0,  o[37],  1 ],  
	// Array
	38, [ o[39] ],  
	// Array
	39, [ 4,  0,  0 ],  
	// Array
	40, [ o[41] ],  
	// Array
	41, [ 4,  0,  0 ],  
	// Array
	42, [ o[43],  o[44],  o[45],  o[46],  
		o[47],  o[48],  o[49],  o[50],  
		o[51] ],  
	// Array
	52, [ 60.0,  56.0,  54.0,  60,  
		62.0,  58.0,  56.0,  46.0,  
		46.0 ],  
	// Dictionary
	53, [ array: o[54],  size: 11 ],  
	// Array
	54, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	55, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	56, [ o[57],  o[58],  o[59],  o[60],  
		o[61],  o[62],  o[63],  o[64],  
		o[65] ],  
	// Array
	57, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	58, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	59, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	60, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	61, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	62, [ 200,  0,  0.707,  561.51429389746,  
		23.035620258383,  4.3114555432853,  12373.26311648,  20.299183623335,  
		8.3600599334693,  false,  12.0 ],  
	// Array
	63, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  10.8 ],  
	// Array
	64, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  8.0 ],  
	// Array
	65, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	66, [ false,  true,  false,  true,  
		true,  false,  false,  true,  
		true ],  
	// Array
	67, [ 3,  5,  15,  0,  
		0,  33,  34,  0,  
		0 ],  
	// Array
	68, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	69, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	70, [ 1.4962356560944,  1.1791044981297,  1.0346965601279,  0.001,  
		0.001,  1.4962356560944,  1.1057207257138,  0.54130277195509,  
		0.77419596608544 ],  
	// Array
	71, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	72, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	73, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	74, [ 0.02289965881948,  0.3,  0.17289965881948,  0.3,  
		0.3,  0.3,  0.3,  0.3,  
		0.3 ]
];
prUnarchive(o,p);
