var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(11),  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(14),  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "lltp",  Array.prNew(3),  "llap",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(6),  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llap",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llap",  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(5),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(9),  
	"CLAVE",  "CATA",  "SHEKERE",  "",  
	"",  "LLAMADOR",  "GOLPE",  "CLAVE",  
	"CLAVE",  Array.prNew(9),  Dictionary.prNew,  Array.prNew(88),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[87],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[97],  'temaBpm',  118.62676056338,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[98],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[100],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[101],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[111],  
		nil,  nil,  nil,  nil,  
		'indices',  o[112],  nil,  nil,  
		nil,  nil,  'humAmp',  o[113],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[114],  
		nil,  nil,  'volumes',  o[115],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[116],  nil,  nil,  
		'montunoIndices',  o[117],  'sampleIndices',  o[118],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[119],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[32],  o[35],  
		o[35],  o[37],  o[66],  o[79],  
		o[81] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.66666666666667,  4,  1 ],  
	// Array
	5, [ 1.0,  4,  1 ],  
	// Array
	6, [ 0.66666666666667,  4,  1 ],  
	// Array
	7, [ 0.66666666666667,  4,  1 ],  
	// Array
	8, [ 1.0,  4,  1 ],  
	// Array
	9, [ o[10],  o[12],  o[14],  o[16],  
		o[18],  o[20],  o[22],  o[24],  
		o[26],  o[28],  o[30] ],  
	// Array
	10, [ 0.25,  o[11],  1 ],  
	// Array
	12, [ 0.5,  o[13],  1 ],  
	// Array
	14, [ 0.25,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.5,  o[19],  1 ],  
	// Array
	20, [ 0.25,  o[21],  1 ],  
	// Array
	22, [ 0.5,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.25,  o[27],  1 ],  
	// Array
	28, [ 0.5,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ o[33],  o[34] ],  
	// Array
	33, [ 0.66666666666667,  7,  1 ],  
	// Array
	34, [ 0.33333333333333,  8,  1 ],  
	// Array
	35, [ o[36] ],  
	// Array
	36, [ 4,  0,  0 ],  
	// Array
	37, [ o[38],  o[40],  o[42],  o[44],  
		o[46],  o[48],  o[50],  o[52],  
		o[54],  o[56],  o[58],  o[60],  
		o[62],  o[64] ],  
	// Array
	38, [ 0.25,  o[39],  0.3 ],  
	// Array
	40, [ 0.25,  o[41],  0.125 ],  
	// Array
	42, [ 0.25,  o[43],  0.125 ],  
	// Array
	44, [ 0.25,  o[45],  0.3 ],  
	// Array
	46, [ 0.25,  o[47],  0.3 ],  
	// Array
	48, [ 0.25,  o[49],  0.125 ],  
	// Array
	50, [ 0.25,  o[51],  0.125 ],  
	// Array
	52, [ 0.25,  o[53],  0.5 ],  
	// Array
	54, [ 0.75,  o[55],  1 ],  
	// Array
	56, [ 0.25,  o[57],  0.3 ],  
	// Array
	58, [ 0.25,  o[59],  0.3 ],  
	// Array
	60, [ 0.25,  o[61],  0.125 ],  
	// Array
	62, [ 0.25,  o[63],  0.125 ],  
	// Array
	64, [ 0.25,  o[65],  0.3 ],  
	// Array
	66, [ o[67],  o[69],  o[71],  o[73],  
		o[75],  o[77] ],  
	// Array
	67, [ 1,  o[68],  0.25 ],  
	// Array
	69, [ 0.5,  o[70],  0.25 ],  
	// Array
	71, [ 0.5,  o[72],  1 ],  
	// Array
	73, [ 1,  o[74],  0.25 ],  
	// Array
	75, [ 0.5,  o[76],  0.25 ],  
	// Array
	77, [ 0.5,  o[78],  1 ],  
	// Array
	79, [ o[80] ],  
	// Array
	80, [ 4,  0,  0 ],  
	// Array
	81, [ o[82],  o[83],  o[84],  o[85],  
		o[86] ],  
	// Array
	82, [ 0.75,  2,  1 ],  
	// Array
	83, [ 1,  2,  1 ],  
	// Array
	84, [ 0.7,  2,  1 ],  
	// Array
	85, [ 0.55,  2,  1 ],  
	// Array
	86, [ 1,  2,  1 ],  
	// Array
	87, [ o[88],  o[89],  o[90],  o[91],  
		o[92],  o[93],  o[94],  o[95],  
		o[96] ],  
	// Array
	97, [ 60.0,  56.0,  54.0,  60,  
		62.0,  58.0,  54.0,  46.0,  
		46.0 ],  
	// Dictionary
	98, [ array: o[99],  size: 11 ],  
	// Array
	99, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	100, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	101, [ o[102],  o[103],  o[104],  o[105],  
		o[106],  o[107],  o[108],  o[109],  
		o[110] ],  
	// Array
	102, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	103, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	104, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	105, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	106, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	107, [ 200,  0,  0.707,  561.51429389746,  
		23.035620258383,  4.3114555432853,  12373.26311648,  20.299183623335,  
		8.3600599334693,  false,  12.0 ],  
	// Array
	108, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  10.8 ],  
	// Array
	109, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  8.0 ],  
	// Array
	110, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	111, [ false,  true,  false,  true,  
		true,  true,  true,  true,  
		true ],  
	// Array
	112, [ 3,  5,  13,  0,  
		0,  22,  15,  0,  
		1 ],  
	// Array
	113, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	114, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	115, [ 1.4962356560944,  1.1791044981297,  1.0346965601279,  0.001,  
		0.001,  1.4962356560944,  1.1057207257138,  0.54130277195509,  
		0.77419596608544 ],  
	// Array
	116, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	117, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	118, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	119, [ 0.02289965881948,  0.3,  0.17289965881948,  0.3,  
		0.3,  0.3,  0.3,  0.3,  
		0.3 ]
];
prUnarchive(o,p);
