var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(7),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(10),  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(8),  Array.prNew(3),  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  Array.prNew(3),  "llsmp",  
	Array.prNew(3),  "llaf",  Array.prNew(3),  "llsmp",  
	Array.prNew(13),  Array.prNew(3),  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjncmf",  
	Array.prNew(3),  "cjncmf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjncf",  
	Array.prNew(3),  "cjncmf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjndf",  Array.prNew(1),  Array.prNew(3),  
	"coro1",  Array.prNew(9),  "Clave",  "Cáscara",  
	"Shekere",  "----",  "----",  "Llamador",  
	"Cajon",  "CORO I",  "CORO II",  Array.prNew(9),  
	Dictionary.prNew,  Array.prNew(88),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  75,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  1,  nil,  nil,  
		'trackNames',  o[81],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[91],  'temaBpm',  74.968652037618,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[92],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  4,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[94],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[95],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[105],  
		nil,  nil,  nil,  nil,  
		'indices',  o[106],  nil,  nil,  
		nil,  nil,  'humAmp',  o[107],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[108],  
		nil,  nil,  'volumes',  o[109],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[110],  nil,  nil,  
		'montunoIndices',  o[111],  'sampleIndices',  o[112],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[113],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[11],  o[32],  o[35],  
		o[35],  o[37],  o[52],  o[78],  
		o[78] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8],  o[9],  o[10] ],  
	// Array
	4, [ 0.75,  2,  1 ],  
	// Array
	5, [ 0.25,  2,  1 ],  
	// Array
	6, [ 0.75,  2,  1 ],  
	// Array
	7, [ 0.25,  2,  1 ],  
	// Array
	8, [ 0.5,  2,  1 ],  
	// Array
	9, [ 0.5,  2,  1 ],  
	// Array
	10, [ 1,  2,  1 ],  
	// Array
	11, [ o[12],  o[14],  o[16],  o[18],  
		o[20],  o[22],  o[24],  o[26],  
		o[28],  o[30] ],  
	// Array
	12, [ 0.5,  o[13],  1 ],  
	// Array
	14, [ 0.25,  o[15],  1 ],  
	// Array
	16, [ 0.5,  o[17],  1 ],  
	// Array
	18, [ 0.5,  o[19],  1 ],  
	// Array
	20, [ 0.25,  o[21],  1 ],  
	// Array
	22, [ 0.5,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.25,  o[27],  1 ],  
	// Array
	28, [ 0.5,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ o[33],  o[34] ],  
	// Array
	33, [ 3.75,  7,  1 ],  
	// Array
	34, [ 0.25,  8,  1 ],  
	// Array
	35, [ o[36] ],  
	// Array
	36, [ 4,  0,  0 ],  
	// Array
	37, [ o[38],  o[39],  o[41],  o[43],  
		o[45],  o[46],  o[48],  o[50] ],  
	// Array
	38, [ 0.25,  0,  0 ],  
	// Array
	39, [ 0.25,  o[40],  1 ],  
	// Array
	41, [ 0.25,  o[42],  1 ],  
	// Array
	43, [ 0.25,  o[44],  1 ],  
	// Array
	45, [ 0.25,  0,  0 ],  
	// Array
	46, [ 0.25,  o[47],  1 ],  
	// Array
	48, [ 0.25,  o[49],  1 ],  
	// Array
	50, [ 0.25,  o[51],  1 ],  
	// Array
	52, [ o[53],  o[54],  o[56],  o[58],  
		o[60],  o[62],  o[64],  o[66],  
		o[68],  o[70],  o[72],  o[74],  
		o[76] ],  
	// Array
	53, [ 0.25,  0,  0 ],  
	// Array
	54, [ 0.25,  o[55],  1 ],  
	// Array
	56, [ 0.25,  o[57],  1 ],  
	// Array
	58, [ 0.25,  o[59],  1 ],  
	// Array
	60, [ 0.25,  o[61],  1 ],  
	// Array
	62, [ 0.5,  o[63],  1 ],  
	// Array
	64, [ 0.25,  o[65],  1 ],  
	// Array
	66, [ 0.5,  o[67],  1 ],  
	// Array
	68, [ 0.25,  o[69],  1 ],  
	// Array
	70, [ 0.25,  o[71],  1 ],  
	// Array
	72, [ 0.25,  o[73],  1 ],  
	// Array
	74, [ 0.5,  o[75],  1 ],  
	// Array
	76, [ 0.25,  o[77],  1 ],  
	// Array
	78, [ o[79] ],  
	// Array
	79, [ 128,  o[80],  1 ],  
	// Array
	81, [ o[82],  o[83],  o[84],  o[85],  
		o[86],  o[87],  o[88],  o[89],  
		o[90] ],  
	// Array
	91, [ 47.0,  54.0,  59.0,  60,  
		59.0,  57.0,  55.0,  47.0,  
		47.0 ],  
	// Dictionary
	92, [ array: o[93],  size: 11 ],  
	// Array
	93, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	94, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	95, [ o[96],  o[97],  o[98],  o[99],  
		o[100],  o[101],  o[102],  o[103],  
		o[104] ],  
	// Array
	96, [ 265.08772819178,  0,  5.1898010283689,  1089.6207143201,  
		6.4962071432007,  2.7394425152227,  3632.4532412149,  8.4313682755227,  
		7.9255406275383,  false,  2.4 ],  
	// Array
	97, [ 200,  0,  0.707,  1110.3448275862,  
		10.758620689655,  8.1763157894737,  14103.448275862,  24,  
		7.9157894736842,  false,  0 ],  
	// Array
	98, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	99, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	100, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	101, [ 200,  0,  0.707,  664.57989548682,  
		6.763790240975,  6.9981960344416,  4603.4482758621,  19.862068965517,  
		4.2684210526316,  false,  12.0 ],  
	// Array
	102, [ 137.79144844185,  20.299183623335,  10,  2351.724137931,  
		6.6206896551724,  0.707,  12137.931034483,  15.724137931034,  
		10,  false,  3.1 ],  
	// Array
	103, [ 200,  8.500816376665,  3.6549682627989,  1000,  
		-11.663563364952,  0.707,  5000,  0,  
		0.707,  false,  2.7 ],  
	// Array
	104, [ 265.08772819178,  0,  5.1898010283689,  1089.6207143201,  
		0.79515851649765,  2.7394425152227,  3632.4532412149,  0.50877281917828,  
		7.9255406275383,  false,  1.8 ],  
	// Array
	105, [ false,  false,  false,  true,  
		true,  false,  false,  false,  
		false ],  
	// Array
	106, [ 2,  6,  10,  0,  
		0,  26,  22,  1,  
		1 ],  
	// Array
	107, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	108, [ 0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339 ],  
	// Array
	109, [ 0.92596587739714,  0.81086425622512,  1.3648527477948,  0.001,  
		0.001,  1.4962356560944,  1.1057207257138,  0.72662629239073,  
		0.38325630647535 ],  
	// Array
	110, [ 0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136 ],  
	// Array
	111, [ 2,  6,  10,  0,  
		0,  24,  21,  0,  
		0 ],  
	// Array
	112, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	113, [ 0.3,  0.3,  0.3,  0.3,  
		0.3,  0.3,  0.3,  0.42987496324859,  
		0.41852015073194 ]
];
prUnarchive(o,p);
