var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(7),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(11),  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(8),  
	Array.prNew(3),  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	Array.prNew(3),  "llsmp",  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "llsmp",  Array.prNew(5),  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llsmf",  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llamf",  Array.prNew(3),  
	"llamf",  Array.prNew(1),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(9),  "CAMPANA",  "-----",  
	"CATA",  "SHEKERE",  "LLAMADOR",  "GOLPE",  
	"-----",  "CHORO",  "CAMPANA",  Array.prNew(9),  
	Dictionary.prNew,  Array.prNew(88),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[69],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[79],  'temaBpm',  102.2323943662,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[80],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[82],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[83],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[93],  
		nil,  nil,  nil,  nil,  
		'indices',  o[94],  nil,  nil,  
		nil,  nil,  'humAmp',  o[95],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[96],  
		nil,  nil,  'volumes',  o[97],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[98],  nil,  nil,  
		'montunoIndices',  o[99],  'sampleIndices',  o[100],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[101],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[11],  o[13],  o[36],  
		o[39],  o[54],  o[11],  o[65],  
		o[67] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8],  o[9],  o[10] ],  
	// Array
	4, [ 0.66666666666667,  4,  1 ],  
	// Array
	5, [ 0.66666666666667,  4,  1 ],  
	// Array
	6, [ 0.33333333333333,  4,  1 ],  
	// Array
	7, [ 0.66666666666667,  4,  1 ],  
	// Array
	8, [ 0.66666666666667,  4,  1 ],  
	// Array
	9, [ 0.66666666666667,  4,  1 ],  
	// Array
	10, [ 0.33333333333333,  4,  1 ],  
	// Array
	11, [ o[12] ],  
	// Array
	12, [ 4,  0,  0 ],  
	// Array
	13, [ o[14],  o[16],  o[18],  o[20],  
		o[22],  o[24],  o[26],  o[28],  
		o[30],  o[32],  o[34] ],  
	// Array
	14, [ 0.5,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.5,  o[19],  1 ],  
	// Array
	20, [ 0.5,  o[21],  1 ],  
	// Array
	22, [ 0.25,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.5,  o[27],  1 ],  
	// Array
	28, [ 0.25,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ 0.25,  o[33],  1 ],  
	// Array
	34, [ 0.25,  o[35],  1 ],  
	// Array
	36, [ o[37],  o[38] ],  
	// Array
	37, [ 0.66666666666667,  7,  1 ],  
	// Array
	38, [ 0.33333333333333,  8,  1 ],  
	// Array
	39, [ o[40],  o[41],  o[43],  o[45],  
		o[47],  o[48],  o[50],  o[52] ],  
	// Array
	40, [ 0.25,  0,  0 ],  
	// Array
	41, [ 0.25,  o[42],  1 ],  
	// Array
	43, [ 0.25,  o[44],  1 ],  
	// Array
	45, [ 0.25,  o[46],  1 ],  
	// Array
	47, [ 0.25,  0,  0 ],  
	// Array
	48, [ 0.25,  o[49],  1 ],  
	// Array
	50, [ 0.25,  o[51],  1 ],  
	// Array
	52, [ 0.25,  o[53],  1 ],  
	// Array
	54, [ o[55],  o[57],  o[59],  o[61],  
		o[63] ],  
	// Array
	55, [ 0.66666666666667,  o[56],  0.43 ],  
	// Array
	57, [ 0.33333333333333,  o[58],  1 ],  
	// Array
	59, [ 0.33333333333333,  o[60],  0.43 ],  
	// Array
	61, [ 0.33333333333333,  o[62],  1 ],  
	// Array
	63, [ 0.33333333333333,  o[64],  1 ],  
	// Array
	65, [ o[66] ],  
	// Array
	66, [ 4,  0,  0 ],  
	// Array
	67, [ o[68] ],  
	// Array
	68, [ 4,  0,  0 ],  
	// Array
	69, [ o[70],  o[71],  o[72],  o[73],  
		o[74],  o[75],  o[76],  o[77],  
		o[78] ],  
	// Array
	79, [ 60,  54.0,  54.0,  57.0,  
		60.0,  55.0,  60,  60,  
		60 ],  
	// Dictionary
	80, [ array: o[81],  size: 11 ],  
	// Array
	81, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	82, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	83, [ o[84],  o[85],  o[86],  o[87],  
		o[88],  o[89],  o[90],  o[91],  
		o[92] ],  
	// Array
	84, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  8.1449825782033,  
		0.707,  false,  5.6 ],  
	// Array
	85, [ 200,  0,  0.707,  1299.9385962009,  
		8.294843746021,  3.2967066223129,  5000,  0,  
		0.707,  false,  0.0 ],  
	// Array
	86, [ 200,  0,  0.707,  768.89672351334,  
		18.650408188332,  5.6915211493298,  8887.3214794148,  11.450408188332,  
		0.89109667829158,  false,  0 ],  
	// Array
	87, [ 200,  0,  0.707,  1160.0,  
		12.320861313293,  2.3482933776871,  5000,  0,  
		0.707,  false,  2.1 ],  
	// Array
	88, [ 205.22182670516,  24,  5.3343163900774,  1260.3790240975,  
		10.640229491848,  8.6055810827991,  2838.962086302,  0.70379285679928,  
		8.9888058669121,  false,  0 ],  
	// Array
	89, [ 206.09589195843,  24,  0.86329337768715,  1437.6643941802,  
		17.888225517816,  4.4644258363731,  2163.2091753506,  10.397297043504,  
		1.2033533111564,  false,  7.2 ],  
	// Array
	90, [ 150.88225517816,  22.978503709466,  0.595,  200,  
		-12.154201045132,  0.44984272328515,  6269.2440658644,  18.019178391686,  
		4.6767722283573,  false,  0 ],  
	// Array
	91, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	92, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  8.1449825782033,  
		0.707,  false,  4.4 ],  
	// Array
	93, [ false,  true,  true,  true,  
		true,  true,  true,  true,  
		true ],  
	// Array
	94, [ 4,  0,  9,  16,  
		30,  20,  0,  0,  
		0 ],  
	// Array
	95, [ 0.01271186440678,  0.01271186440678,  0.01271186440678,  0.01271186440678,  
		0.01271186440678,  0.01271186440678,  0.01271186440678,  0.01271186440678,  
		0.01271186440678 ],  
	// Array
	96, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	97, [ 1.3014265162018,  0.001,  0.61430900727822,  0.96603200137215,  
		0.91279927128521,  0.96603200137215,  0.001,  0.72662629239073,  
		1.3014265162018 ],  
	// Array
	98, [ 0.090909090909091,  0.27272727272727,  0.31818181818182,  0.11440677966102,  
		0.11440677966102,  0.11440677966102,  0.22727272727273,  0.22727272727273,  
		0.22727272727273 ],  
	// Array
	99, [ 3,  0,  9,  16,  
		31,  21,  0,  0,  
		3 ],  
	// Array
	100, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	101, [ 0.3123002250866,  0.2,  0.26852015073194,  0.3,  
		0.2,  0.10315131966974,  0.14684868033026,  0.26144982940974,  
		0.29684868033026 ]
];
prUnarchive(o,p);
