var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(9),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(9),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(4),  
	Array.prNew(3),  "lltp",  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "lltp",  Array.prNew(3),  Array.prNew(6),  
	Array.prNew(3),  Array.prNew(3),  "llsf",  Array.prNew(3),  
	"llsf",  Array.prNew(3),  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "llaf",  Array.prNew(3),  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llaf",  Array.prNew(1),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(9),  "CAMPANA 1",  "CAMPANA 2",  
	"CAMPANA3A",  "CAMPANA3B",  "",  "LLAMADOR",  
	"GOLPE",  "CLAVE",  "CLAVE",  Array.prNew(9),  
	Dictionary.prNew,  Array.prNew(88),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[61],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[71],  'temaBpm',  138.87323943662,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[72],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[74],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[75],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[85],  
		nil,  nil,  nil,  nil,  
		'indices',  o[86],  nil,  nil,  
		nil,  nil,  'humAmp',  o[87],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[88],  
		nil,  nil,  'volumes',  o[89],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[90],  nil,  nil,  
		'montunoIndices',  o[91],  'sampleIndices',  o[92],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[93],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[11],  o[21],  
		o[31],  o[39],  o[50],  o[57],  
		o[59] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.66666666666667,  4,  1 ],  
	// Array
	5, [ 1.0,  4,  1 ],  
	// Array
	6, [ 0.66666666666667,  4,  1 ],  
	// Array
	7, [ 0.66666666666667,  4,  1 ],  
	// Array
	8, [ 1.0,  4,  1 ],  
	// Array
	9, [ o[10] ],  
	// Array
	10, [ 0.5,  0,  1 ],  
	// Array
	11, [ o[12],  o[13],  o[14],  o[15],  
		o[16],  o[17],  o[18],  o[19],  
		o[20] ],  
	// Array
	12, [ 0.25,  4,  0 ],  
	// Array
	13, [ 0.25,  4,  1 ],  
	// Array
	14, [ 0.5,  4,  1 ],  
	// Array
	15, [ 0.5,  4,  0 ],  
	// Array
	16, [ 0.5,  4,  0 ],  
	// Array
	17, [ 0.5,  4,  1 ],  
	// Array
	18, [ 0.5,  4,  1 ],  
	// Array
	19, [ 0.75,  4,  0 ],  
	// Array
	20, [ 0.25,  4,  1 ],  
	// Array
	21, [ o[22],  o[23],  o[24],  o[25],  
		o[26],  o[27],  o[28],  o[29],  
		o[30] ],  
	// Array
	22, [ 0.25,  4,  0 ],  
	// Array
	23, [ 0.25,  4,  0 ],  
	// Array
	24, [ 0.5,  4,  0 ],  
	// Array
	25, [ 0.5,  4,  1 ],  
	// Array
	26, [ 0.5,  4,  1 ],  
	// Array
	27, [ 0.5,  4,  0 ],  
	// Array
	28, [ 0.5,  4,  0 ],  
	// Array
	29, [ 0.75,  4,  1 ],  
	// Array
	30, [ 0.25,  4,  1 ],  
	// Array
	31, [ o[32],  o[34],  o[36],  o[38] ],  
	// Array
	32, [ 0.66666666666667,  o[33],  1 ],  
	// Array
	34, [ 0.33333333333333,  o[35],  1 ],  
	// Array
	36, [ 0.66666666666667,  o[37],  1 ],  
	// Array
	38, [ 0.33333333333333,  0,  0 ],  
	// Array
	39, [ o[40],  o[41],  o[43],  o[45],  
		o[46],  o[48] ],  
	// Array
	40, [ 0.33333333333333,  0,  0 ],  
	// Array
	41, [ 0.33333333333333,  o[42],  1 ],  
	// Array
	43, [ 0.33333333333333,  o[44],  1 ],  
	// Array
	45, [ 0.33333333333333,  0,  0 ],  
	// Array
	46, [ 0.33333333333333,  o[47],  1 ],  
	// Array
	48, [ 0.33333333333333,  o[49],  1 ],  
	// Array
	50, [ o[51],  o[53],  o[55] ],  
	// Array
	51, [ 1,  o[52],  1 ],  
	// Array
	53, [ 0.66666666666667,  o[54],  1 ],  
	// Array
	55, [ 0.33333333333333,  o[56],  1 ],  
	// Array
	57, [ o[58] ],  
	// Array
	58, [ 4,  0,  0 ],  
	// Array
	59, [ o[60] ],  
	// Array
	60, [ 4,  0,  0 ],  
	// Array
	61, [ o[62],  o[63],  o[64],  o[65],  
		o[66],  o[67],  o[68],  o[69],  
		o[70] ],  
	// Array
	71, [ 60.0,  56.0,  66.0,  65.0,  
		38.0,  58.0,  54.0,  46.0,  
		46.0 ],  
	// Dictionary
	72, [ array: o[73],  size: 11 ],  
	// Array
	73, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	74, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	75, [ o[76],  o[77],  o[78],  o[79],  
		o[80],  o[81],  o[82],  o[83],  
		o[84] ],  
	// Array
	76, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  3.7 ],  
	// Array
	77, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0.8 ],  
	// Array
	78, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  -4.6 ],  
	// Array
	79, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  7.2 ],  
	// Array
	80, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  5.4 ],  
	// Array
	81, [ 200,  0,  0.707,  561.51429389746,  
		23.035620258383,  4.3114555432853,  12373.26311648,  20.299183623335,  
		8.3600599334693,  false,  -12.0 ],  
	// Array
	82, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  -4.2 ],  
	// Array
	83, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  8.0 ],  
	// Array
	84, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	85, [ false,  false,  false,  false,  
		false,  false,  false,  true,  
		true ],  
	// Array
	86, [ 3,  41,  5,  6,  
		39,  38,  24,  0,  
		0 ],  
	// Array
	87, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	88, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	89, [ 1.4962356560944,  1.1791044981297,  1.0346965601279,  1.0770279066598,  
		0.97957614457689,  0.86107668956953,  1.0207748798303,  0.54130277195509,  
		0.77419596608544 ],  
	// Array
	90, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	91, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	92, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	93, [ 0.15321252177358,  0.3,  0.17289965881948,  0.3,  
		0.3,  0.3,  0.3,  0.3,  
		0.3 ]
];
prUnarchive(o,p);
