var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(2),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(9),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(1),  Array.prNew(3),  Array.prNew(4),  Array.prNew(3),  
	Array.prNew(3),  "cjncmf",  Array.prNew(3),  "cjncmf",  
	Array.prNew(3),  "cjndf",  Array.prNew(4),  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llcmf",  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llaf",  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(9),  
	"CLAVE",  "CATA",  "SHEKERE",  "",  
	"",  "LLAMADOR",  "GOLPE",  "CLAVE",  
	"CLAVE",  Array.prNew(9),  Dictionary.prNew,  Array.prNew(88),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[47],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[57],  'temaBpm',  132.35915492958,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[58],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[60],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[61],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[71],  
		nil,  nil,  nil,  nil,  
		'indices',  o[72],  nil,  nil,  
		nil,  nil,  'humAmp',  o[73],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[74],  
		nil,  nil,  'volumes',  o[75],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[76],  nil,  nil,  
		'montunoIndices',  o[77],  'sampleIndices',  o[78],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[79],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[11],  o[14],  
		o[24],  o[26],  o[34],  o[43],  
		o[45] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.66666666666667,  4,  1 ],  
	// Array
	5, [ 1.0,  4,  1 ],  
	// Array
	6, [ 0.66666666666667,  4,  1 ],  
	// Array
	7, [ 0.66666666666667,  4,  1 ],  
	// Array
	8, [ 1.0,  4,  1 ],  
	// Array
	9, [ o[10] ],  
	// Array
	10, [ 0.5,  0,  1 ],  
	// Array
	11, [ o[12],  o[13] ],  
	// Array
	12, [ 0.75,  7,  1 ],  
	// Array
	13, [ 0.25,  8,  1 ],  
	// Array
	14, [ o[15],  o[16],  o[17],  o[18],  
		o[19],  o[20],  o[21],  o[22],  
		o[23] ],  
	// Array
	15, [ 0.25,  4,  0 ],  
	// Array
	16, [ 0.25,  4,  1 ],  
	// Array
	17, [ 0.5,  4,  1 ],  
	// Array
	18, [ 0.5,  4,  1 ],  
	// Array
	19, [ 0.5,  4,  1 ],  
	// Array
	20, [ 0.5,  4,  1 ],  
	// Array
	21, [ 0.5,  4,  1 ],  
	// Array
	22, [ 0.75,  4,  1 ],  
	// Array
	23, [ 0.25,  4,  1 ],  
	// Array
	24, [ o[25] ],  
	// Array
	25, [ 4,  0,  0 ],  
	// Array
	26, [ o[27],  o[28],  o[30],  o[32] ],  
	// Array
	27, [ 0.75,  0,  0 ],  
	// Array
	28, [ 0.25,  o[29],  1 ],  
	// Array
	30, [ 0.5,  o[31],  1 ],  
	// Array
	32, [ 0.5,  o[33],  1 ],  
	// Array
	34, [ o[35],  o[37],  o[39],  o[41] ],  
	// Array
	35, [ 0.75,  o[36],  1 ],  
	// Array
	37, [ 0.25,  o[38],  1 ],  
	// Array
	39, [ 0.5,  o[40],  1 ],  
	// Array
	41, [ 0.5,  o[42],  1 ],  
	// Array
	43, [ o[44] ],  
	// Array
	44, [ 4,  0,  0 ],  
	// Array
	45, [ o[46] ],  
	// Array
	46, [ 4,  0,  0 ],  
	// Array
	47, [ o[48],  o[49],  o[50],  o[51],  
		o[52],  o[53],  o[54],  o[55],  
		o[56] ],  
	// Array
	57, [ 62.0,  56.0,  54.0,  60,  
		62.0,  58.0,  54.0,  46.0,  
		46.0 ],  
	// Dictionary
	58, [ array: o[59],  size: 11 ],  
	// Array
	59, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	60, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	61, [ o[62],  o[63],  o[64],  o[65],  
		o[66],  o[67],  o[68],  o[69],  
		o[70] ],  
	// Array
	62, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0.0 ],  
	// Array
	63, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	64, [ 200,  0,  0.707,  1000,  
		-18.233998235933,  2.4791269835414,  5000,  -9.589026748502,  
		0.707,  false,  0 ],  
	// Array
	65, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	66, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	67, [ 200,  0,  0.707,  561.51429389746,  
		23.035620258383,  4.3114555432853,  12373.26311648,  20.299183623335,  
		8.3600599334693,  false,  12.0 ],  
	// Array
	68, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  10.8 ],  
	// Array
	69, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  8.0 ],  
	// Array
	70, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	71, [ false,  false,  true,  true,  
		true,  true,  true,  true,  
		true ],  
	// Array
	72, [ 3,  33,  13,  5,  
		0,  22,  15,  0,  
		0 ],  
	// Array
	73, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	74, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	75, [ 1.4962356560944,  1.4962356560944,  1.0913271240502,  0.001,  
		0.001,  1.4962356560944,  1.1057207257138,  0.54130277195509,  
		0.77419596608544 ],  
	// Array
	76, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	77, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	78, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	79, [ 0.02289965881948,  0.0,  0.17289965881948,  0.3,  
		0.3,  0.3,  0.3,  0.3,  
		0.3 ]
];
prUnarchive(o,p);
