var o, p;
o = [
	Dictionary.prNew,  Array.prNew(64),  Array.prNew(7),  Array.prNew(7),  
	Array.prNew(5),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(2),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(11),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(4),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(6),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(7),  Array.prNew(7),  Array.prNew(7),  Array.prNew(7),  
	Array.prNew(7),  Array.prNew(7),  Array.prNew(7)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 10 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[2],  
		'rhythms',  o[3],  nil,  nil,  
		'bpm',  128.68338557994,  'indices',  o[40],  
		nil,  nil,  'humAmp',  o[41],  
		nil,  nil,  nil,  nil,  
		'pitches',  o[42],  'humTime',  o[43],  
		nil,  nil,  'volumes',  o[44],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[45],  nil,  nil,  
		nil,  nil,  'sampleIndices',  o[46],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ true,  true,  true,  true,  
		false,  true,  true ],  
	// Array
	3, [ o[4],  o[10],  o[13],  o[25],  
		o[28],  o[33],  o[4] ],  
	// Array
	4, [ o[5],  o[6],  o[7],  o[8],  
		o[9] ],  
	// Array
	5, [ 0.75,  2,  1 ],  
	// Array
	6, [ 1,  2,  1 ],  
	// Array
	7, [ 0.7,  2,  1 ],  
	// Array
	8, [ 0.55,  2,  1 ],  
	// Array
	9, [ 1,  2,  1 ],  
	// Array
	10, [ o[11],  o[12] ],  
	// Array
	11, [ 0.5,  0,  1 ],  
	// Array
	12, [ 0.5,  0,  1 ],  
	// Array
	13, [ o[14],  o[15],  o[16],  o[17],  
		o[18],  o[19],  o[20],  o[21],  
		o[22],  o[23],  o[24] ],  
	// Array
	14, [ 0.25,  0,  1 ],  
	// Array
	15, [ 0.5,  0,  1 ],  
	// Array
	16, [ 0.25,  0,  1 ],  
	// Array
	17, [ 0.25,  0,  1 ],  
	// Array
	18, [ 0.5,  0,  1 ],  
	// Array
	19, [ 0.25,  0,  1 ],  
	// Array
	20, [ 0.5,  0,  1 ],  
	// Array
	21, [ 0.5,  0,  1 ],  
	// Array
	22, [ 0.25,  0,  1 ],  
	// Array
	23, [ 0.5,  0,  1 ],  
	// Array
	24, [ 0.25,  0,  1 ],  
	// Array
	25, [ o[26],  o[27] ],  
	// Array
	26, [ 1.75,  7,  1 ],  
	// Array
	27, [ 0.25,  8,  1 ],  
	// Array
	28, [ o[29],  o[30],  o[31],  o[32] ],  
	// Array
	29, [ 0.25,  1,  0.5 ],  
	// Array
	30, [ 0.25,  10,  0.5 ],  
	// Array
	31, [ 0.25,  10,  0.5 ],  
	// Array
	32, [ 0.25,  1,  0.5 ],  
	// Array
	33, [ o[34],  o[35],  o[36],  o[37],  
		o[38],  o[39] ],  
	// Array
	34, [ 1,  1,  0.135 ],  
	// Array
	35, [ 0.5,  1,  0.135 ],  
	// Array
	36, [ 0.5,  3,  1 ],  
	// Array
	37, [ 1,  1,  0.135 ],  
	// Array
	38, [ 0.5,  1,  0.135 ],  
	// Array
	39, [ 0.5,  3,  1 ],  
	// Array
	40, [ 0,  0,  4,  18,  
		14,  10,  0 ],  
	// Array
	41, [ 0.035593220338983,  0.035593220338983,  0.035593220338983,  0.035593220338983,  
		0.035593220338983,  0.035593220338983,  0.035593220338983 ],  
	// Array
	42, [ 46.0,  60,  62.0,  60,  
		60,  59.0,  46.0 ],  
	// Array
	43, [ 0.017627118644068,  0.017627118644068,  0.017627118644068,  0.017627118644068,  
		0,  0.017627118644068,  0.017627118644068 ],  
	// Array
	44, [ 0.54130277195509,  0.7,  1.4962356560944,  0.7,  
		1.4962356560944,  0.82327578815141,  0.54130277195509 ],  
	// Array
	45, [ 0.19067796610169,  0.19067796610169,  0.19067796610169,  0.19067796610169,  
		0.19067796610169,  0.19067796610169,  0.19067796610169 ],  
	// Array
	46, [ 0,  1,  2,  3,  
		4,  5,  0 ]
];
prUnarchive(o,p);
