var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(11),  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(14),  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "lltp",  Array.prNew(3),  "llap",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(6),  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llap",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llap",  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(9),  "CLAVE",  "CATA",  
	"SHEKERE",  "",  "",  "LLAMADOR",  
	"GOLPE",  "CLAVE",  "CLAVE",  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 19 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  nil,  nil,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[81],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[91],  'temaBpm',  122.10031347962,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[92],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[93],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[103],  
		nil,  nil,  nil,  nil,  
		'indices',  o[104],  nil,  nil,  
		nil,  nil,  'humAmp',  o[105],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'humTime',  o[106],  
		nil,  nil,  'volumes',  o[107],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[108],  nil,  nil,  
		'montunoIndices',  o[109],  'sampleIndices',  o[110],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[32],  o[35],  
		o[35],  o[37],  o[66],  o[79],  
		o[3] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.75,  2,  1 ],  
	// Array
	5, [ 1,  2,  1 ],  
	// Array
	6, [ 0.7,  2,  1 ],  
	// Array
	7, [ 0.55,  2,  1 ],  
	// Array
	8, [ 1,  2,  1 ],  
	// Array
	9, [ o[10],  o[12],  o[14],  o[16],  
		o[18],  o[20],  o[22],  o[24],  
		o[26],  o[28],  o[30] ],  
	// Array
	10, [ 0.25,  o[11],  1 ],  
	// Array
	12, [ 0.5,  o[13],  1 ],  
	// Array
	14, [ 0.25,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.5,  o[19],  1 ],  
	// Array
	20, [ 0.25,  o[21],  1 ],  
	// Array
	22, [ 0.5,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.25,  o[27],  1 ],  
	// Array
	28, [ 0.5,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ o[33],  o[34] ],  
	// Array
	33, [ 1.75,  7,  1 ],  
	// Array
	34, [ 0.25,  8,  1 ],  
	// Array
	35, [ o[36] ],  
	// Array
	36, [ 4,  0,  0 ],  
	// Array
	37, [ o[38],  o[40],  o[42],  o[44],  
		o[46],  o[48],  o[50],  o[52],  
		o[54],  o[56],  o[58],  o[60],  
		o[62],  o[64] ],  
	// Array
	38, [ 0.25,  o[39],  0.3 ],  
	// Array
	40, [ 0.25,  o[41],  0.125 ],  
	// Array
	42, [ 0.25,  o[43],  0.125 ],  
	// Array
	44, [ 0.25,  o[45],  0.3 ],  
	// Array
	46, [ 0.25,  o[47],  0.3 ],  
	// Array
	48, [ 0.25,  o[49],  0.125 ],  
	// Array
	50, [ 0.25,  o[51],  0.125 ],  
	// Array
	52, [ 0.25,  o[53],  0.5 ],  
	// Array
	54, [ 0.75,  o[55],  1 ],  
	// Array
	56, [ 0.25,  o[57],  0.3 ],  
	// Array
	58, [ 0.25,  o[59],  0.3 ],  
	// Array
	60, [ 0.25,  o[61],  0.125 ],  
	// Array
	62, [ 0.25,  o[63],  0.125 ],  
	// Array
	64, [ 0.25,  o[65],  0.3 ],  
	// Array
	66, [ o[67],  o[69],  o[71],  o[73],  
		o[75],  o[77] ],  
	// Array
	67, [ 1,  o[68],  0.25 ],  
	// Array
	69, [ 0.5,  o[70],  0.25 ],  
	// Array
	71, [ 0.5,  o[72],  1 ],  
	// Array
	73, [ 1,  o[74],  0.25 ],  
	// Array
	75, [ 0.5,  o[76],  0.25 ],  
	// Array
	77, [ 0.5,  o[78],  1 ],  
	// Array
	79, [ o[80] ],  
	// Array
	80, [ 4,  0,  0 ],  
	// Array
	81, [ o[82],  o[83],  o[84],  o[85],  
		o[86],  o[87],  o[88],  o[89],  
		o[90] ],  
	// Array
	91, [ 46.0,  56.0,  62.0,  60,  
		62.0,  57.0,  54.0,  46.0,  
		46.0 ],  
	// Array
	92, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	93, [ o[94],  o[95],  o[96],  o[97],  
		o[98],  o[99],  o[100],  o[101],  
		o[102] ],  
	// Array
	94, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	95, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	96, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	97, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	98, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	99, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  10.4 ],  
	// Array
	100, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  10.8 ],  
	// Array
	101, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  8.0 ],  
	// Array
	102, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	103, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	104, [ 1,  5,  11,  0,  
		0,  22,  15,  0,  
		1 ],  
	// Array
	105, [ 0.040677966101695,  0.040677966101695,  0.040677966101695,  0.040677966101695,  
		0.040677966101695,  0,  0.040677966101695,  0.040677966101695,  
		0.040677966101695 ],  
	// Array
	106, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	107, [ 0.77419596608544,  1.1791044981297,  0.84838200482362,  0.001,  
		0.001,  1.4962356560944,  1.1057207257138,  0.54130277195509,  
		0.77419596608544 ],  
	// Array
	108, [ 0.41949152542373,  0.41949152542373,  0.41949152542373,  0.41949152542373,  
		0.41949152542373,  0,  0.41949152542373,  0.41949152542373,  
		0.41949152542373 ],  
	// Array
	109, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	110, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ]
];
prUnarchive(o,p);
