var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(7),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(11),  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(2),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(6),  
	Array.prNew(3),  Array.prNew(3),  "llsp",  Array.prNew(3),  
	"llsp",  Array.prNew(3),  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "llsp",  Array.prNew(4),  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llcmf",  Array.prNew(3),  
	"llcmf",  Array.prNew(3),  "llaf",  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(9),  
	"Clave",  "Cáscara",  "Shekere",  "----",  
	"----",  "Llamador",  "Golpe",  "CORO",  
	"Clave",  Array.prNew(9),  Dictionary.prNew,  Array.prNew(88),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 23 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  'reverbWetGain',  0.65,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[63],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[73],  'temaBpm',  92.535211267606,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  'reverbParams',  o[74],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[76],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[77],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[87],  
		nil,  nil,  nil,  nil,  
		'indices',  o[88],  nil,  nil,  
		nil,  nil,  'humAmp',  o[89],  
		'reverbEnabled',  true,  nil,  nil,  
		nil,  nil,  'humTime',  o[90],  
		nil,  nil,  'volumes',  o[91],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[92],  nil,  nil,  
		'montunoIndices',  o[93],  'sampleIndices',  o[94],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'reverbSends',  o[95],  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[11],  o[34],  o[37],  
		o[37],  o[39],  o[50],  o[59],  
		o[61] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8],  o[9],  o[10] ],  
	// Array
	4, [ 0.75,  2,  1 ],  
	// Array
	5, [ 0.25,  2,  1 ],  
	// Array
	6, [ 0.75,  2,  1 ],  
	// Array
	7, [ 0.25,  2,  1 ],  
	// Array
	8, [ 0.5,  2,  1 ],  
	// Array
	9, [ 0.5,  2,  1 ],  
	// Array
	10, [ 1,  2,  1 ],  
	// Array
	11, [ o[12],  o[14],  o[16],  o[18],  
		o[20],  o[22],  o[24],  o[26],  
		o[28],  o[30],  o[32] ],  
	// Array
	12, [ 0.25,  o[13],  1 ],  
	// Array
	14, [ 0.5,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.25,  o[19],  1 ],  
	// Array
	20, [ 0.5,  o[21],  1 ],  
	// Array
	22, [ 0.25,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.5,  o[27],  1 ],  
	// Array
	28, [ 0.25,  o[29],  1 ],  
	// Array
	30, [ 0.5,  o[31],  1 ],  
	// Array
	32, [ 0.25,  o[33],  1 ],  
	// Array
	34, [ o[35],  o[36] ],  
	// Array
	35, [ 1.75,  7,  1 ],  
	// Array
	36, [ 0.25,  8,  1 ],  
	// Array
	37, [ o[38] ],  
	// Array
	38, [ 4,  0,  0 ],  
	// Array
	39, [ o[40],  o[41],  o[43],  o[45],  
		o[46],  o[48] ],  
	// Array
	40, [ 0.46875,  0,  0 ],  
	// Array
	41, [ 0.28125,  o[42],  1 ],  
	// Array
	43, [ 0.25,  o[44],  1 ],  
	// Array
	45, [ 0.46875,  0,  0 ],  
	// Array
	46, [ 0.28125,  o[47],  1 ],  
	// Array
	48, [ 0.25,  o[49],  1 ],  
	// Array
	50, [ o[51],  o[53],  o[55],  o[57] ],  
	// Array
	51, [ 0.75,  o[52],  1 ],  
	// Array
	53, [ 0.25,  o[54],  1 ],  
	// Array
	55, [ 0.5,  o[56],  1 ],  
	// Array
	57, [ 0.5,  o[58],  1 ],  
	// Array
	59, [ o[60] ],  
	// Array
	60, [ 4,  0,  0 ],  
	// Array
	61, [ o[62] ],  
	// Array
	62, [ 4,  0,  0 ],  
	// Array
	63, [ o[64],  o[65],  o[66],  o[67],  
		o[68],  o[69],  o[70],  o[71],  
		o[72] ],  
	// Array
	73, [ 47.0,  56.0,  59.0,  60,  
		59.0,  58.0,  57.0,  47.0,  
		47.0 ],  
	// Dictionary
	74, [ array: o[75],  size: 11 ],  
	// Array
	75, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'size',  1.2,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'earlyDiff',  0.75,  
		nil,  nil,  'modFreq',  0.8,  
		'modDepth',  0.15,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'damp',  0.45,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'mid',  0.7,  'highcut',  3500,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		't60',  1.8,  nil,  nil,  
		'low',  0.9,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'high',  0.4,  nil,  nil,  
		nil,  nil,  'lowcut',  400 ],  
	// Array
	76, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	77, [ o[78],  o[79],  o[80],  o[81],  
		o[82],  o[83],  o[84],  o[85],  
		o[86] ],  
	// Array
	78, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  0,  
		0.707,  false,  0.7 ],  
	// Array
	79, [ 200,  0,  0.707,  1299.9385962009,  
		8.294843746021,  3.2967066223129,  5000,  0,  
		0.707,  false,  0.0 ],  
	// Array
	80, [ 200,  0,  0.707,  1089.6207143201,  
		18.019178391686,  3.0063920688831,  4285.0935175701,  6.763790240975,  
		2.4200599334693,  false,  0 ],  
	// Array
	81, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	82, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	83, [ 265.38633706149,  9.8223264534456,  4.1733533111564,  695.12633441477,  
		18.650408188332,  6.948450654402,  1548.454522759,  15.453111144828,  
		1.8117066223129,  false,  3.0 ],  
	// Array
	84, [ 203.13971553284,  14.4,  0.595,  200,  
		2.0358969096676,  0.44984272328515,  6269.2440658644,  10.149591811668,  
		4.6767722283573,  false,  7.6 ],  
	// Array
	85, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	86, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  0,  
		0.707,  false,  0.7 ],  
	// Array
	87, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	88, [ 2,  7,  13,  0,  
		0,  26,  16,  0,  
		0 ],  
	// Array
	89, [ 0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915,  
		0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915,  
		0.027966101694915 ],  
	// Array
	90, [ 0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339 ],  
	// Array
	91, [ 1.4962356560944,  1.3488546134867,  0.41798971901434,  0.001,  
		0.001,  0.76216197125196,  0.61430900727822,  0.71496983465007,  
		1.1057207257138 ],  
	// Array
	92, [ 0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136 ],  
	// Array
	93, [ 2,  7,  13,  0,  
		0,  27,  17,  0,  
		2 ],  
	// Array
	94, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ],  
	// Array
	95, [ 0.02289965881948,  0.0,  0.17289965881948,  0.3,  
		0.3,  0.0,  0.0,  0.3,  
		0.3 ]
];
prUnarchive(o,p);
