var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(7),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(11),  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(2),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(8),  Array.prNew(3),  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  Array.prNew(3),  "llsmp",  
	Array.prNew(3),  "llaf",  Array.prNew(3),  "llsmp",  
	Array.prNew(4),  Array.prNew(3),  Array.prNew(3),  "llcf",  
	Array.prNew(3),  "llcf",  Array.prNew(3),  "llcf",  
	Array.prNew(6),  Array.prNew(3),  Array.prNew(3),  "llsp",  
	Array.prNew(3),  "llsp",  Array.prNew(3),  Array.prNew(3),  
	"llaf",  Array.prNew(3),  "llsp",  Array.prNew(4),  
	Array.prNew(3),  "llcmf",  Array.prNew(3),  "llcmf",  
	Array.prNew(3),  "llcmf",  Array.prNew(3),  "llaf",  
	Array.prNew(1),  Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  
	Array.prNew(9),  "Clave",  "Cáscara",  "Shekere",  
	"----",  "----",  "Llamador",  "Golpe",  
	"CORO",  "Clave",  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 19 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  105,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  nil,  nil,  
		'choirSetIdx',  0,  nil,  nil,  
		'trackNames',  o[84],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[94],  'temaBpm',  92.535211267606,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  -1,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[95],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[96],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[106],  
		nil,  nil,  nil,  nil,  
		'indices',  o[107],  nil,  nil,  
		nil,  nil,  'humAmp',  o[108],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'humTime',  o[109],  
		nil,  nil,  'volumes',  o[110],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[111],  nil,  nil,  
		'montunoIndices',  o[112],  'sampleIndices',  o[113],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[11],  o[34],  o[37],  
		o[52],  o[60],  o[71],  o[80],  
		o[82] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8],  o[9],  o[10] ],  
	// Array
	4, [ 0.75,  2,  1 ],  
	// Array
	5, [ 0.25,  2,  1 ],  
	// Array
	6, [ 0.75,  2,  1 ],  
	// Array
	7, [ 0.25,  2,  1 ],  
	// Array
	8, [ 0.5,  2,  1 ],  
	// Array
	9, [ 0.5,  2,  1 ],  
	// Array
	10, [ 1,  2,  1 ],  
	// Array
	11, [ o[12],  o[14],  o[16],  o[18],  
		o[20],  o[22],  o[24],  o[26],  
		o[28],  o[30],  o[32] ],  
	// Array
	12, [ 0.25,  o[13],  1 ],  
	// Array
	14, [ 0.5,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.25,  o[19],  1 ],  
	// Array
	20, [ 0.5,  o[21],  1 ],  
	// Array
	22, [ 0.25,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.5,  o[27],  1 ],  
	// Array
	28, [ 0.25,  o[29],  1 ],  
	// Array
	30, [ 0.5,  o[31],  1 ],  
	// Array
	32, [ 0.25,  o[33],  1 ],  
	// Array
	34, [ o[35],  o[36] ],  
	// Array
	35, [ 3.75,  7,  1 ],  
	// Array
	36, [ 0.25,  8,  1 ],  
	// Array
	37, [ o[38],  o[39],  o[41],  o[43],  
		o[45],  o[46],  o[48],  o[50] ],  
	// Array
	38, [ 0.25,  0,  0 ],  
	// Array
	39, [ 0.25,  o[40],  1 ],  
	// Array
	41, [ 0.25,  o[42],  1 ],  
	// Array
	43, [ 0.25,  o[44],  1 ],  
	// Array
	45, [ 0.25,  0,  0 ],  
	// Array
	46, [ 0.25,  o[47],  1 ],  
	// Array
	48, [ 0.25,  o[49],  1 ],  
	// Array
	50, [ 0.25,  o[51],  1 ],  
	// Array
	52, [ o[53],  o[54],  o[56],  o[58] ],  
	// Array
	53, [ 0.75,  0,  0 ],  
	// Array
	54, [ 0.25,  o[55],  1 ],  
	// Array
	56, [ 1,  o[57],  1 ],  
	// Array
	58, [ 2,  o[59],  1 ],  
	// Array
	60, [ o[61],  o[62],  o[64],  o[66],  
		o[67],  o[69] ],  
	// Array
	61, [ 0.46875,  0,  0 ],  
	// Array
	62, [ 0.28125,  o[63],  1 ],  
	// Array
	64, [ 0.25,  o[65],  1 ],  
	// Array
	66, [ 0.46875,  0,  0 ],  
	// Array
	67, [ 0.28125,  o[68],  1 ],  
	// Array
	69, [ 0.25,  o[70],  1 ],  
	// Array
	71, [ o[72],  o[74],  o[76],  o[78] ],  
	// Array
	72, [ 0.75,  o[73],  1 ],  
	// Array
	74, [ 0.25,  o[75],  1 ],  
	// Array
	76, [ 0.5,  o[77],  1 ],  
	// Array
	78, [ 0.5,  o[79],  1 ],  
	// Array
	80, [ o[81] ],  
	// Array
	81, [ 4,  0,  0 ],  
	// Array
	82, [ o[83] ],  
	// Array
	83, [ 4,  0,  0 ],  
	// Array
	84, [ o[85],  o[86],  o[87],  o[88],  
		o[89],  o[90],  o[91],  o[92],  
		o[93] ],  
	// Array
	94, [ 47.0,  56.0,  59.0,  60,  
		59.0,  58.0,  57.0,  47.0,  
		47.0 ],  
	// Array
	95, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	96, [ o[97],  o[98],  o[99],  o[100],  
		o[101],  o[102],  o[103],  o[104],  
		o[105] ],  
	// Array
	97, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  0,  
		0.707,  false,  0.7 ],  
	// Array
	98, [ 200,  0,  0.707,  1299.9385962009,  
		8.294843746021,  3.2967066223129,  5000,  0,  
		0.707,  false,  0.0 ],  
	// Array
	99, [ 200,  0,  0.707,  1089.6207143201,  
		18.019178391686,  3.0063920688831,  4285.0935175701,  6.763790240975,  
		2.4200599334693,  false,  0 ],  
	// Array
	100, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	101, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	102, [ 265.38633706149,  9.8223264534456,  4.1733533111564,  695.12633441477,  
		18.650408188332,  6.948450654402,  1548.454522759,  15.453111144828,  
		1.8117066223129,  false,  3.0 ],  
	// Array
	103, [ 203.13971553284,  8.2612023384222,  0.595,  200,  
		2.0358969096676,  0.44984272328515,  6269.2440658644,  10.149591811668,  
		4.6767722283573,  false,  7.6 ],  
	// Array
	104, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	105, [ 200,  0,  0.707,  811.17744821837,  
		4.810973251498,  2.9566466888436,  5000,  0,  
		0.707,  false,  0.7 ],  
	// Array
	106, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	107, [ 2,  5,  10,  25,  
		15,  24,  14,  0,  
		0 ],  
	// Array
	108, [ 0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915,  
		0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915,  
		0.027966101694915 ],  
	// Array
	109, [ 0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339 ],  
	// Array
	110, [ 1.1057207257138,  1.0346965601279,  0.73837713440461,  0.001,  
		0.001,  1.0346965601279,  0.96603200137215,  0.71496983465007,  
		1.1057207257138 ],  
	// Array
	111, [ 0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136 ],  
	// Array
	112, [ 2,  5,  12,  0,  
		0,  25,  15,  0,  
		2 ],  
	// Array
	113, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ]
];
prUnarchive(o,p);
