var o, p;
o = [
	Dictionary.prNew,  Array.prNew(128),  Array.prNew(9),  Array.prNew(5),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(11),  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(2),  Array.prNew(3),  Array.prNew(3),  Array.prNew(1),  
	Array.prNew(3),  Array.prNew(14),  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "lltp",  Array.prNew(3),  "llap",  
	Array.prNew(3),  "llcp",  Array.prNew(3),  "llcp",  
	Array.prNew(3),  "llpp",  Array.prNew(3),  "llpp",  
	Array.prNew(3),  "llcp",  Array.prNew(6),  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llap",  Array.prNew(3),  "llcp",  Array.prNew(3),  
	"llcp",  Array.prNew(3),  "llap",  Array.prNew(1),  
	Array.prNew(3),  "coro1",  Array.prNew(9),  "CLAVE",  
	"CATA",  "SHEKERE",  "",  "",  
	"LLAMADOR",  "GOLPE",  "CLAVE",  "CLAVE",  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  Array.prNew(11),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  
	Array.prNew(9),  Array.prNew(9),  Array.prNew(9),  Array.prNew(9)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 19 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'chorusRefBpm',  140,  nil,  nil,  
		'choirSetIdx2',  0,  nil,  nil,  
		'rhythms',  o[2],  nil,  nil,  
		'choirSetIdx',  1,  nil,  nil,  
		'trackNames',  o[82],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		'pitches',  o[92],  'temaBpm',  130.0,  
		nil,  nil,  nil,  nil,  
		'seccion',  'tema',  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'currentSongIdx',  3,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'solos',  o[93],  
		nil,  nil,  nil,  nil,  
		'eqParams',  o[94],  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'mutes',  o[104],  
		nil,  nil,  nil,  nil,  
		'indices',  o[105],  nil,  nil,  
		nil,  nil,  'humAmp',  o[106],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  'humTime',  o[107],  
		nil,  nil,  'volumes',  o[108],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[109],  nil,  nil,  
		'montunoIndices',  o[110],  'sampleIndices',  o[111],  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[9],  o[32],  o[35],  
		o[35],  o[37],  o[66],  o[79],  
		o[79] ],  
	// Array
	3, [ o[4],  o[5],  o[6],  o[7],  
		o[8] ],  
	// Array
	4, [ 0.75,  2,  1 ],  
	// Array
	5, [ 1,  2,  1 ],  
	// Array
	6, [ 0.7,  2,  1 ],  
	// Array
	7, [ 0.55,  2,  1 ],  
	// Array
	8, [ 1,  2,  1 ],  
	// Array
	9, [ o[10],  o[12],  o[14],  o[16],  
		o[18],  o[20],  o[22],  o[24],  
		o[26],  o[28],  o[30] ],  
	// Array
	10, [ 0.25,  o[11],  1 ],  
	// Array
	12, [ 0.5,  o[13],  1 ],  
	// Array
	14, [ 0.25,  o[15],  1 ],  
	// Array
	16, [ 0.25,  o[17],  1 ],  
	// Array
	18, [ 0.5,  o[19],  1 ],  
	// Array
	20, [ 0.25,  o[21],  1 ],  
	// Array
	22, [ 0.5,  o[23],  1 ],  
	// Array
	24, [ 0.5,  o[25],  1 ],  
	// Array
	26, [ 0.25,  o[27],  1 ],  
	// Array
	28, [ 0.5,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ o[33],  o[34] ],  
	// Array
	33, [ 1.75,  7,  1 ],  
	// Array
	34, [ 0.25,  8,  1 ],  
	// Array
	35, [ o[36] ],  
	// Array
	36, [ 4,  0,  0 ],  
	// Array
	37, [ o[38],  o[40],  o[42],  o[44],  
		o[46],  o[48],  o[50],  o[52],  
		o[54],  o[56],  o[58],  o[60],  
		o[62],  o[64] ],  
	// Array
	38, [ 0.25,  o[39],  0.3 ],  
	// Array
	40, [ 0.25,  o[41],  0.125 ],  
	// Array
	42, [ 0.25,  o[43],  0.125 ],  
	// Array
	44, [ 0.25,  o[45],  0.3 ],  
	// Array
	46, [ 0.25,  o[47],  0.3 ],  
	// Array
	48, [ 0.25,  o[49],  0.125 ],  
	// Array
	50, [ 0.25,  o[51],  0.125 ],  
	// Array
	52, [ 0.25,  o[53],  0.5 ],  
	// Array
	54, [ 0.75,  o[55],  1 ],  
	// Array
	56, [ 0.25,  o[57],  0.3 ],  
	// Array
	58, [ 0.25,  o[59],  0.3 ],  
	// Array
	60, [ 0.25,  o[61],  0.125 ],  
	// Array
	62, [ 0.25,  o[63],  0.125 ],  
	// Array
	64, [ 0.25,  o[65],  0.3 ],  
	// Array
	66, [ o[67],  o[69],  o[71],  o[73],  
		o[75],  o[77] ],  
	// Array
	67, [ 1,  o[68],  0.25 ],  
	// Array
	69, [ 0.5,  o[70],  0.25 ],  
	// Array
	71, [ 0.5,  o[72],  1 ],  
	// Array
	73, [ 1,  o[74],  0.25 ],  
	// Array
	75, [ 0.5,  o[76],  0.25 ],  
	// Array
	77, [ 0.5,  o[78],  1 ],  
	// Array
	79, [ o[80] ],  
	// Array
	80, [ 16,  o[81],  1 ],  
	// Array
	82, [ o[83],  o[84],  o[85],  o[86],  
		o[87],  o[88],  o[89],  o[90],  
		o[91] ],  
	// Array
	92, [ 46.0,  56.0,  62.0,  60,  
		62.0,  58.0,  54.0,  46.0,  
		46.0 ],  
	// Array
	93, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	94, [ o[95],  o[96],  o[97],  o[98],  
		o[99],  o[100],  o[101],  o[102],  
		o[103] ],  
	// Array
	95, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	96, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	97, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	98, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	99, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  0 ],  
	// Array
	100, [ 200,  0,  0.707,  561.51429389746,  
		23.035620258383,  4.3114555432853,  12373.26311648,  20.299183623335,  
		8.3600599334693,  false,  12.0 ],  
	// Array
	101, [ 232.63563364952,  8.500816376665,  1.3414555432853,  1000,  
		13.9835900476,  3.4750317372011,  9661.4337387048,  14.4,  
		2.2148253537392,  false,  10.8 ],  
	// Array
	102, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  4.5 ],  
	// Array
	103, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false,  2.8 ],  
	// Array
	104, [ false,  false,  false,  false,  
		false,  false,  false,  false,  
		false ],  
	// Array
	105, [ 1,  5,  11,  0,  
		0,  23,  16,  1,  
		1 ],  
	// Array
	106, [ 0.040677966101695,  0.040677966101695,  0.040677966101695,  0.040677966101695,  
		0.040677966101695,  0,  0.040677966101695,  0.040677966101695,  
		0.040677966101695 ],  
	// Array
	107, [ 0,  0,  0,  0,  
		0,  0,  0,  0,  
		0 ],  
	// Array
	108, [ 1.4962356560944,  1.1791044981297,  0.84838200482362,  0.001,  
		0.001,  1.4962356560944,  1.4962356560944,  0.93922686778227,  
		0.99321467205484 ],  
	// Array
	109, [ 0.41949152542373,  0.41949152542373,  0.41949152542373,  0.41949152542373,  
		0.41949152542373,  0,  0.41949152542373,  0.41949152542373,  
		0.41949152542373 ],  
	// Array
	110, [ 1,  5,  11,  0,  
		0,  24,  15,  0,  
		1 ],  
	// Array
	111, [ 0,  1,  2,  3,  
		4,  5,  0,  0,  
		0 ]
];
prUnarchive(o,p);
