var o, p;
o = [
	Dictionary.prNew,  Array.prNew(64),  Array.prNew(8),  Array.prNew(10),  
	Array.prNew(10),  Array.prNew(10),  Array.prNew(10),  Array.prNew(10),  
	Array.prNew(10),  Array.prNew(10),  Array.prNew(10),  Array.prNew(8),  
	Array.prNew(8),  Array.prNew(7),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(10),  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(3),  "cf",  
	Array.prNew(3),  "cf",  Array.prNew(2),  Array.prNew(3),  
	Array.prNew(3),  Array.prNew(1),  Array.prNew(3),  Array.prNew(8),  
	Array.prNew(3),  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	"llsmp",  Array.prNew(3),  "llsmp",  Array.prNew(3),  
	Array.prNew(3),  "llsmp",  Array.prNew(3),  "llaf",  
	Array.prNew(3),  "llsmp",  Array.prNew(13),  Array.prNew(3),  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjncmf",  Array.prNew(3),  "cjncmf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjndf",  
	Array.prNew(3),  "cjncf",  Array.prNew(3),  "cjncmf",  
	Array.prNew(3),  "cjndf",  Array.prNew(3),  "cjndf",  
	Array.prNew(1),  Array.prNew(3),  "coro2",  Array.prNew(8),  
	Array.prNew(8),  "Clave",  "Cáscara",  "Shekere",  
	"----",  "----",  "Llamador",  "Cajon",  
	"CORO",  Array.prNew(8),  Array.prNew(8),  Array.prNew(8),  
	Array.prNew(8),  Array.prNew(8),  Array.prNew(8)
];
p = [
	// Dictionary
	0, [ array: o[1],  size: 14 ],  
	// Array
	1, [ nil,  nil,  nil,  nil,  
		'eqParams',  o[2],  nil,  nil,  
		'chorusRefBpm',  80,  nil,  nil,  
		nil,  nil,  'mutes',  o[11],  
		'rhythms',  o[12],  nil,  nil,  
		'bpm',  79.968652037618,  'indices',  o[91],  
		'trackNames',  o[92],  'humAmp',  o[101],  
		nil,  nil,  nil,  nil,  
		'pitches',  o[102],  'humTime',  o[103],  
		nil,  nil,  'volumes',  o[104],  
		nil,  nil,  nil,  nil,  
		'humPitch',  o[105],  nil,  nil,  
		nil,  nil,  'sampleIndices',  o[106],  
		'currentSongIdx',  1,  nil,  nil,  
		nil,  nil,  nil,  nil,  
		nil,  nil,  nil,  nil ],  
	// Array
	2, [ o[3],  o[4],  o[5],  o[6],  
		o[7],  o[8],  o[9],  o[10] ],  
	// Array
	3, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false ],  
	// Array
	4, [ 200,  0,  0.707,  1110.3448275862,  
		10.758620689655,  8.1763157894737,  14103.448275862,  24,  
		7.9157894736842,  false ],  
	// Array
	5, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false ],  
	// Array
	6, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false ],  
	// Array
	7, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false ],  
	// Array
	8, [ 200,  0,  0.707,  2848.275862069,  
		0,  4.7894736842105,  4603.4482758621,  19.862068965517,  
		4.2684210526316,  false ],  
	// Array
	9, [ 94.48275862069,  24,  10,  2351.724137931,  
		6.6206896551724,  0.707,  12137.931034483,  15.724137931034,  
		10,  false ],  
	// Array
	10, [ 200,  0,  0.707,  1000,  
		0,  0.707,  5000,  0,  
		0.707,  false ],  
	// Array
	11, [ false,  false,  false,  false,  
		false,  false,  false,  false ],  
	// Array
	12, [ o[13],  o[21],  o[42],  o[45],  
		o[45],  o[47],  o[62],  o[88] ],  
	// Array
	13, [ o[14],  o[15],  o[16],  o[17],  
		o[18],  o[19],  o[20] ],  
	// Array
	14, [ 0.75,  2,  1 ],  
	// Array
	15, [ 0.25,  2,  1 ],  
	// Array
	16, [ 0.75,  2,  1 ],  
	// Array
	17, [ 0.25,  2,  1 ],  
	// Array
	18, [ 0.5,  2,  1 ],  
	// Array
	19, [ 0.5,  2,  1 ],  
	// Array
	20, [ 1,  2,  1 ],  
	// Array
	21, [ o[22],  o[24],  o[26],  o[28],  
		o[30],  o[32],  o[34],  o[36],  
		o[38],  o[40] ],  
	// Array
	22, [ 0.5,  o[23],  1 ],  
	// Array
	24, [ 0.25,  o[25],  1 ],  
	// Array
	26, [ 0.5,  o[27],  1 ],  
	// Array
	28, [ 0.5,  o[29],  1 ],  
	// Array
	30, [ 0.25,  o[31],  1 ],  
	// Array
	32, [ 0.5,  o[33],  1 ],  
	// Array
	34, [ 0.5,  o[35],  1 ],  
	// Array
	36, [ 0.25,  o[37],  1 ],  
	// Array
	38, [ 0.5,  o[39],  1 ],  
	// Array
	40, [ 0.25,  o[41],  1 ],  
	// Array
	42, [ o[43],  o[44] ],  
	// Array
	43, [ 3.75,  7,  1 ],  
	// Array
	44, [ 0.25,  8,  1 ],  
	// Array
	45, [ o[46] ],  
	// Array
	46, [ 4,  0,  0 ],  
	// Array
	47, [ o[48],  o[49],  o[51],  o[53],  
		o[55],  o[56],  o[58],  o[60] ],  
	// Array
	48, [ 0.25,  0,  0 ],  
	// Array
	49, [ 0.25,  o[50],  1 ],  
	// Array
	51, [ 0.25,  o[52],  1 ],  
	// Array
	53, [ 0.25,  o[54],  1 ],  
	// Array
	55, [ 0.25,  0,  0 ],  
	// Array
	56, [ 0.25,  o[57],  1 ],  
	// Array
	58, [ 0.25,  o[59],  1 ],  
	// Array
	60, [ 0.25,  o[61],  1 ],  
	// Array
	62, [ o[63],  o[64],  o[66],  o[68],  
		o[70],  o[72],  o[74],  o[76],  
		o[78],  o[80],  o[82],  o[84],  
		o[86] ],  
	// Array
	63, [ 0.25,  0,  0 ],  
	// Array
	64, [ 0.25,  o[65],  1 ],  
	// Array
	66, [ 0.25,  o[67],  1 ],  
	// Array
	68, [ 0.25,  o[69],  1 ],  
	// Array
	70, [ 0.25,  o[71],  1 ],  
	// Array
	72, [ 0.5,  o[73],  1 ],  
	// Array
	74, [ 0.25,  o[75],  1 ],  
	// Array
	76, [ 0.5,  o[77],  1 ],  
	// Array
	78, [ 0.25,  o[79],  1 ],  
	// Array
	80, [ 0.25,  o[81],  1 ],  
	// Array
	82, [ 0.25,  o[83],  1 ],  
	// Array
	84, [ 0.5,  o[85],  1 ],  
	// Array
	86, [ 0.25,  o[87],  1 ],  
	// Array
	88, [ o[89] ],  
	// Array
	89, [ 16,  o[90],  1 ],  
	// Array
	91, [ 2,  6,  10,  0,  
		0,  24,  21,  1 ],  
	// Array
	92, [ o[93],  o[94],  o[95],  o[96],  
		o[97],  o[98],  o[99],  o[100] ],  
	// Array
	101, [ 0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915,  
		0.027966101694915,  0.027966101694915,  0.027966101694915,  0.027966101694915 ],  
	// Array
	102, [ 47.0,  54.0,  59.0,  60,  
		59.0,  57.0,  59.0,  47.0 ],  
	// Array
	103, [ 0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  
		0.0088135593220339,  0.0088135593220339,  0.0088135593220339,  0.0088135593220339 ],  
	// Array
	104, [ 1.1057207257138,  1.1494678363437,  1.3648527477948,  1.3971321692305,  
		0.7,  1.3488546134867,  1.4962356560944,  0.96603200137215 ],  
	// Array
	105, [ 0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136,  
		0.15254237288136,  0.15254237288136,  0.15254237288136,  0.15254237288136 ],  
	// Array
	106, [ 0,  1,  2,  3,  
		4,  5,  0,  0 ]
];
prUnarchive(o,p);
